### ISSUE TITLE
Vacor's ring

### ISSUE THREAD

**Issue by doczkal** [AndorsTrailRelease/andors-trail#13]
(I failed to register a forum account and hope someone will see this)

I noticed that "Vacor's Ring" is shown as "Category: Other" on the "Info" Page of the object but when you filter your Inventory for object types it's shown in "Quest Item" which is correct considering that you have to return the ring to Unzel.

**Comment by Rijackson** [comment]
The quest item is a type setting, which is separate to category. So for example you could have a sword that's a quest item, or a ring that's a quest item. When these were created they were just left as category "other", so they have no properties.

**Comment by Chriz76** [comment]
Actually, no we can't change it. If it's a ring you could equip it, which would break the quest.
