### ISSUE TITLE
Probably mistype in AndroidStorage.java

### ISSUE THREAD

**Issue by vorobiev-xyz** [AndorsTrailRelease/andors-trail#40]
https://github.com/AndorsTrailRelease/andors-trail/blob/master/AndorsTrail/src/com/gpl/rpg/AndorsTrail/util/AndroidStorage.java#L20

```
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.FROYO && Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
```

Second condition is always true if the first one is also true. Probably here should be less-or-equal.
I suppose this could be a reason of the following crash: https://andorstrail.com/viewtopic.php?t=7292

**Comment by Chriz76** [comment]
Thank you for reporting this. The froyo condition doesn't make sense. But as far as I remember the outcome is ok and the code path is only entered for Q and up. But I will have to check if that is what I intended.

**Comment by NutAndor** [comment]
manually merged
