### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [AndorsTrailRelease/andors-trail#41]
https://monitor.f-droid.org/builds/log/com.gpl.rpg.AndorsTrail/64#site-footer

Could you please take a look? Thanks!

**Comment by licaon-kter** [comment]
I've removed the "faulty" line _(reading https://stackoverflow.com/a/63365334 and https://medium.com/androiddevelopers/android-11-storage-faq-78cefea52b7c I'm not sure `preserve...` is even useful)_ and it goes on further but fails elsewhere.

@linsui we have in extlib that .jar for android-support but that appears to be older _(2013 vs the Andord 2016 version)_ and smaller (>900Kb vs 1.4Mb Andors). And clearly it misses some functions:
```
    [javac] /home/vagrant/build/com.gpl.rpg.AndorsTrail/AndorsTrail/src/com/gpl/rpg/AndorsTrail/util/AndroidStorage.java:7: error: cannot find symbol
    [javac] import android.support.v4.content.FileProvider;
    [javac]                                  ^
    [javac]   symbol:   class FileProvider
    [javac]   location: package android.support.v4.content
    [javac] /home/vagrant/build/com.gpl.rpg.AndorsTrail/AndorsTrail/src/com/gpl/rpg/AndorsTrail/util/AndroidStorage.java:102: error: cannot find symbol
    [javac]             Uri uri = FileProvider.getUriForFile(context, "com.gpl.rpg.AndorsTrail.fileprovider", worldmap);
    [javac]                       ^
    [javac]   symbol:   variable FileProvider
    [javac]   location: class AndroidStorage
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] 2 errors
    [javac] 3 warnings
```

**Comment by linsui** [comment]
> /LE: interesting... https://github.com/AndorsTrailRelease/andors-trail/blob/master/travis/support/script

Does this work?

**Comment by licaon-kter** [comment]
No joy.

Basically I'm not sure which version of https://mvnrepository.com/artifact/com.android.support/support-v4 should be used.

I've tried several and they all fail differently.
* If older they don't recognize `requestLegacyExternalStorage` and `preserveLegacyExternalStorage`.
* If they do know what those are it complains about `AAPT: error: resource android:attr/fontStyle not found`
* or `Resource and asset merger: The file name must end with .xml` _(.tmx in https://github.com/AndorsTrailRelease/andors-trail/tree/master/AndorsTrail/res/xml)_

**Comment by goodevilgenius** [comment]
So, is the F-Droid build no longer supported?

**Comment by ravea** [comment]
> So, is the F-Droid build no longer supported?

https://github.com/AndorsTrailRelease/andors-trail/pull/47 this pull restore support F-Droid

Need to ask them to update the f-droid build? @NutAndor

**Comment by NutAndor** [comment]
Hi Ravea,
F-Droid wasn't supported with the latest releases. But we now have the engine modernized a bit and use Gradle for compile.
I am working on a new release with some bugfixes and full Gradle usage. The Gradle part is working already and the rest should be ready in a few days. I plan to tag it in github as v0.8.2 then, because I thought that you only use tagged sources.
But maybe you want to check it manually first?
I don't know if your PR will be necessary, but nevertheless I will have a look at it...

16.10.2022 21:15:51 ravea ***@***.***>:

**Comment by licaon-kter** [comment]
Merged


/close this
