### ISSUE TITLE
Proposal for PR: Humanize save game format

### ISSUE THREAD

**Issue by Lazalatin** [AndorsTrailRelease/andors-trail#64]
Hi there,
As I was once stuck with a lost save game and no way to restore my experience with the game I tried to have a look on a typical Andors Trail save game. Unfortunately it was a wild mix of UTF-8 and binary stuff, and it still is today.

Looking at the code I realized, that this seemed to be intentional. Also a type of obscurity-based anti-cheat feature is implemented into the saving mechanism. I want to propose a different approach to which end I will prepare a PR for this project and maybe get involved even more.

I propose changing the format into plain JSON, maybe even JSON5 to have some additional features. XML is also a possibility, but I would rather not. I would also implement tests for the feature and add a migration class too, to migrate old save game formats on runtime.

This will remove any "security" against tempering with the save game. Why one even bothered preventing players from tempering, goes beyond me. If players wanted to, they could have used the OS code here from this repo and implement a stable load and resave mechanism (or a separate app for it) using https://github.com/AndorsTrailRelease/andors-trail/blob/master/AndorsTrail/app/src/main/java/com/gpl/rpg/AndorsTrail/savegames/Savegames.java

Additionally, as an argument: I would like to be able to experience the game the way I want to. If I am stuck at Lodars house for example - as many have been before I am sure - I do not want to farm the first couple ghosts at the cave for hours and hours to get the abilities to get through them. Just open the save game, change the spawn to the bed in my fathers house and get on with it.
If people want to have infinite skill points and levels and the best equipment for their character build, let them. Skipping the grinding and all the quests, to achieve their desired char build is their loss of a beautifully authored game. I think it is no responsibility of the game to prevent them from doing that. (As Andors Trail is in no way multiplayer or competitive anyways)

Let me know what you think. I am eager to start :)

**Comment by NutAndor** [comment]
This "obsurity" isn't intentional. If we wanted to block players from changing savegames, we would have done it properly, so that you wouldn't find anything...
But we also don't want to support savegame editing too much or make it too easy. So we don't want to change the savegames structure.
Thanks for your offer to work on the game though :)
